// Writes index.html's module preload hints: a <link rel="modulepreload"> for
// every module the first page load needs, so the browser requests them all
// as soon as it reads the page. Without them it finds the modules one import
// at a time, fetching a module before it learns what that module imports,
// about twenty requests deep.
//
//   node scripts/modulepreload.mjs          rewrite the hints in index.html
//   node scripts/modulepreload.mjs --check  exit 1 if they are out of date
//
// The first load is ui/boot.js, ui/start.js (which boot.js imports) and
// ui/main.js (which start.js imports once storage is open), with every module
// they reach through static imports.
// Pages and service groups are left out: they are imported with import()
// when first needed (ui/router/index.js, ui/main.js), and preloading them
// would load them with the app again. A preload fetches and parses a module
// without running it, so ui/start.js still runs ui/main.js only after storage
// is open. tests/ModulePreload.test.js fails when the hints are out of date.
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { ROOT, staticGraph } from './moduleGraph.mjs';

export const FIRST_LOAD_ENTRIES = ['ui/boot.js', 'ui/start.js', 'ui/main.js'];
const START = '<!-- modulepreload:start';
const END = '<!-- modulepreload:end -->';
const INDENT = '    ';

// Breadth first from the entries, so what the page needs first is asked for
// first.
export function firstLoadModules() {
    return [...staticGraph(...FIRST_LOAD_ENTRIES)];
}

function hintBlock(modules) {
    return [
        `${START} (generated by scripts/modulepreload.mjs; run it after changing imports) -->`,
        ...modules.map((file) => `${INDENT}<link rel="modulepreload" href="${file}">`),
        `${INDENT}${END}`
    ].join('\n');
}

function withHints(html, modules) {
    const start = html.indexOf(START);
    const end = html.indexOf(END);
    if (start < 0 || end < start) throw new Error(`index.html has no ${START} … ${END} block`);
    return html.slice(0, start) + hintBlock(modules) + html.slice(end + END.length);
}

// The modules index.html preloads, in order.
export function preloadedModules(html) {
    const start = html.indexOf(START);
    const end = html.indexOf(END);
    if (start < 0 || end < start) return [];
    return [...html.slice(start, end).matchAll(/<link rel="modulepreload" href="([^"]+)">/g)].map((m) => m[1]);
}

// Empty when index.html's hints are exactly what this script would write.
export function modulePreloadDifferences(html = readFileSync(path.join(ROOT, 'index.html'), 'utf8')) {
    const expected = firstLoadModules();
    const actual = preloadedModules(html);
    const differences = [
        ...expected.filter((file) => !actual.includes(file)).map((file) => `missing: ${file}`),
        ...actual.filter((file) => !expected.includes(file)).map((file) => `not in the first load: ${file}`)
    ];
    if (differences.length === 0 && withHints(html, expected) !== html) differences.push('the hints are out of order');
    return differences;
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(ROOT, 'scripts/modulepreload.mjs')) {
    const file = path.join(ROOT, 'index.html');
    const html = readFileSync(file, 'utf8');
    if (process.argv.includes('--check')) {
        const differences = modulePreloadDifferences(html);
        if (differences.length > 0) {
            console.error(`index.html's module preload hints are out of date (run node scripts/modulepreload.mjs):\n  ${differences.slice(0, 20).join('\n  ')}`);
            process.exit(1);
        }
        console.log(`index.html preloads the ${preloadedModules(html).length} modules of the first load.`);
    } else {
        const modules = firstLoadModules();
        writeFileSync(file, withHints(html, modules));
        console.log(`index.html now preloads ${modules.length} modules.`);
    }
}
